<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttendanceSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // ATTENDANCE CAPTURE METHODS
            [
                'key' => 'single_method_only',
                'category' => 'capture_methods',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Single Method Only',
                'description' => 'Restrict to only one attendance capture method',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'allowed_methods',
                'category' => 'capture_methods',
                'value' => '["manual","mobile","biometric","web_based"]',
                'type' => 'json',
                'label' => 'Allowed Capture Methods',
                'description' => 'Select allowed methods for capturing attendance',
                'validation_rules' => json_encode(['required', 'json']),
                'display_order' => 2,
            ],
            
            // WORKING DAYS CONFIGURATION
            [
                'key' => 'working_days',
                'category' => 'working_days',
                'value' => '["sunday","monday","tuesday","wednesday","thursday"]',
                'type' => 'json',
                'label' => 'Working Days',
                'description' => 'Select which days are regular working days',
                'validation_rules' => json_encode(['required', 'json']),
                'display_order' => 1,
            ],
            
            // TIME RULES
            [
                'key' => 'work_day_start_time',
                'category' => 'time_rules',
                'value' => '08:00',
                'type' => 'time',
                'label' => 'Work Day Start Time',
                'description' => 'Official start time of the work day',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 1,
            ],
            [
                'key' => 'work_day_end_time',
                'category' => 'time_rules',
                'value' => '17:00',
                'type' => 'time',
                'label' => 'Work Day End Time',
                'description' => 'Official end time of the work day',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 2,
            ],
            [
                'key' => 'grace_period_minutes',
                'category' => 'time_rules',
                'value' => '15',
                'type' => 'integer',
                'label' => 'Grace Period (Minutes)',
                'description' => 'Minutes allowed after start time before considered late',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:60']),
                'display_order' => 3,
            ],
            [
                'key' => 'minimum_work_hours',
                'category' => 'time_rules',
                'value' => '8',
                'type' => 'float',
                'label' => 'Minimum Work Hours Per Day',
                'description' => 'Minimum hours required for a full work day',
                'validation_rules' => json_encode(['required', 'numeric', 'min:1', 'max:24']),
                'display_order' => 4,
            ],
            [
                'key' => 'auto_clockout_enabled',
                'category' => 'time_rules',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Auto Clock-Out Enabled',
                'description' => 'Automatically clock out employees who forget',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'auto_clockout_time',
                'category' => 'time_rules',
                'value' => '23:59',
                'type' => 'time',
                'label' => 'Auto Clock-Out Time',
                'description' => 'Time to automatically clock out employees',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 6,
            ],

            // LOCATION RULES
            [
                'key' => 'require_gps',
                'category' => 'location_rules',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Require GPS for Clock-In',
                'description' => 'Employees must provide GPS coordinates to clock in',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'enable_geofencing',
                'category' => 'location_rules',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Enable Geofencing',
                'description' => 'Restrict clock-in to specific locations',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'allowed_locations',
                'category' => 'location_rules',
                'value' => '[]',
                'type' => 'json',
                'label' => 'Allowed Locations',
                'description' => 'List of allowed locations with coordinates and radius',
                'validation_rules' => json_encode(['nullable', 'json']),
                'display_order' => 3,
            ],
            [
                'key' => 'location_radius_meters',
                'category' => 'location_rules',
                'value' => '100',
                'type' => 'integer',
                'label' => 'Location Radius (Meters)',
                'description' => 'Acceptable distance from allowed location',
                'validation_rules' => json_encode(['required', 'integer', 'min:10', 'max:1000']),
                'display_order' => 4,
            ],
            [
                'key' => 'allow_remote_work',
                'category' => 'location_rules',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Allow Remote Work',
                'description' => 'Allow employees to clock in from any location',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],

            // PENALTIES
            [
                'key' => 'late_arrival_penalty_enabled',
                'category' => 'penalties',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Late Arrival Penalty Enabled',
                'description' => 'Apply penalty for late arrivals',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'late_arrival_penalty_amount',
                'category' => 'penalties',
                'value' => '0',
                'type' => 'float',
                'label' => 'Late Arrival Penalty Amount',
                'description' => 'Penalty amount for arriving late (currency)',
                'validation_rules' => json_encode(['required', 'numeric', 'min:0']),
                'display_order' => 2,
            ],
            [
                'key' => 'early_departure_penalty_enabled',
                'category' => 'penalties',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Early Departure Penalty Enabled',
                'description' => 'Apply penalty for leaving early',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'early_departure_penalty_amount',
                'category' => 'penalties',
                'value' => '0',
                'type' => 'float',
                'label' => 'Early Departure Penalty Amount',
                'description' => 'Penalty amount for leaving early (currency)',
                'validation_rules' => json_encode(['required', 'numeric', 'min:0']),
                'display_order' => 4,
            ],
            [
                'key' => 'missing_clockout_penalty_enabled',
                'category' => 'penalties',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Missing Clock-Out Penalty Enabled',
                'description' => 'Apply penalty for forgetting to clock out',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'missing_clockout_penalty_amount',
                'category' => 'penalties',
                'value' => '0',
                'type' => 'float',
                'label' => 'Missing Clock-Out Penalty Amount',
                'description' => 'Penalty amount for missing clock-out (currency)',
                'validation_rules' => json_encode(['required', 'numeric', 'min:0']),
                'display_order' => 6,
            ],

            // SHIFT MANAGEMENT
            [
                'key' => 'shifts_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Enable Shifts',
                'description' => 'Use shift-based attendance tracking',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'shift_mode',
                'category' => 'shifts',
                'value' => 'mandatory',
                'type' => 'string',
                'label' => 'Shift Assignment Mode',
                'description' => 'How shifts are assigned to employees',
                'validation_rules' => json_encode(['required', 'in:mandatory,optional,disabled']),
                'display_order' => 2,
            ],
            [
                'key' => 'grace_in_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Grace Period (In) Enabled',
                'description' => 'Allow buffer time for clock-in',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'grace_in_minutes',
                'category' => 'shifts',
                'value' => '10',
                'type' => 'integer',
                'label' => 'Grace Period (In) Minutes',
                'description' => 'Minutes allowed after shift start',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:60']),
                'display_order' => 4,
            ],
            [
                'key' => 'grace_out_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Grace Period (Out) Enabled',
                'description' => 'Allow buffer time for clock-out',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'grace_out_minutes',
                'category' => 'shifts',
                'value' => '10',
                'type' => 'integer',
                'label' => 'Grace Period (Out) Minutes',
                'description' => 'Minutes allowed before shift end',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:60']),
                'display_order' => 6,
            ],
            [
                'key' => 'night_shift_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Night Shift Support',
                'description' => 'Support for shifts crossing midnight',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 7,
            ],
            [
                'key' => 'night_time_start',
                'category' => 'shifts',
                'value' => '22:00',
                'type' => 'time',
                'label' => 'Night Time Start',
                'description' => 'Start of restricted night time range',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 8,
            ],
            [
                'key' => 'night_time_end',
                'category' => 'shifts',
                'value' => '06:00',
                'type' => 'time',
                'label' => 'Night Time End',
                'description' => 'End of restricted night time range',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 9,
            ],
            [
                'key' => 'rotational_shift_enabled',
                'category' => 'shifts',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Rotational Shifts',
                'description' => 'Auto-rotate employee shifts',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 8,
            ],
            [
                'key' => 'flexible_hours_enabled',
                'category' => 'shifts',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Flexible Hours',
                'description' => 'Allow employees to choose work timing',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 9,
            ],
            [
                'key' => 'split_shift_enabled',
                'category' => 'shifts',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Split Shifts',
                'description' => 'Support for shifts with breaks',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 10,
            ],

            // ATTENDANCE POLICIES
            [
                'key' => 'late_arrival_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Late Arrival Rules',
                'description' => 'Enable penalties for late arrival',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'early_checkout_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Early Checkout Rules',
                'description' => 'Enable penalties for early departure',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'half_day_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Half Day',
                'description' => 'Enable half day attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'absence_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Absence Tracking',
                'description' => 'Track employee absences',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 4,
            ],
            [
                'key' => 'overtime_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Overtime',
                'description' => 'Track and compensate extra hours',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'wfh_enabled',
                'category' => 'policies',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Work from Home',
                'description' => 'Enable remote work attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 6,
            ],
            [
                'key' => 'comp_off_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Compensatory Off',
                'description' => 'Earn leave for extra work',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 7,
            ],

            // APPROVALS & WORKFLOW
            [
                'key' => 'missed_punch_approval_enabled',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Missed Punch Requests',
                'description' => 'Allow employees to request corrections',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'correction_approval_enabled',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Attendance Corrections',
                'description' => 'HR/Manager can modify attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'overtime_approval_enabled',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Overtime Approval',
                'description' => 'Require approval for overtime',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'auto_approval_enabled',
                'category' => 'approvals',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Auto-Approval',
                'description' => 'Automatically approve based on rules',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 4,
            ],

            // INTEGRATIONS
            [
                'key' => 'leave_integration_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Leave Integration',
                'description' => 'Sync with leave management',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'holiday_integration_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Holiday Calendar',
                'description' => 'Auto-mark holidays',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'payroll_lock_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Payroll Lock',
                'description' => 'Lock attendance for payroll',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'payroll_export_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Payroll Export',
                'description' => 'Export data for payroll processing',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 4,
            ],

            // AUDIT & SECURITY
            [
                'key' => 'audit_logging_enabled',
                'category' => 'audit_security',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Audit Logging',
                'description' => 'Track all attendance changes',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'audit_level',
                'category' => 'audit_security',
                'value' => 'standard',
                'type' => 'string',
                'label' => 'Logging Level',
                'description' => 'Detail level for audit logs',
                'validation_rules' => json_encode(['required', 'in:minimal,standard,detailed,forensic']),
                'display_order' => 2,
            ],
            [
                'key' => 'tamper_detection_enabled',
                'category' => 'audit_security',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Tamper Detection',
                'description' => 'Detect fraudulent attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'compliance_mode',
                'category' => 'audit_security',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Compliance Mode',
                'description' => 'SOC2, ISO, labor law compliance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 4,
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('attendance_settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
