<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttendanceSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // ATTENDANCE CAPTURE METHODS
            [
                'key' => 'single_method_only',
                'category' => 'capture_methods',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Single Method Only',
                'description' => 'Restrict to only one attendance capture method',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'allowed_methods',
                'category' => 'capture_methods',
                'value' => '["manual","mobile","biometric","web_based"]',
                'type' => 'json',
                'label' => 'Allowed Capture Methods',
                'description' => 'Select allowed methods for capturing attendance',
                'validation_rules' => json_encode(['required', 'json']),
                'display_order' => 2,
            ],
            
            // WORKING DAYS CONFIGURATION
            [
                'key' => 'working_days',
                'category' => 'working_days',
                'value' => '["sunday","monday","tuesday","wednesday","thursday"]',
                'type' => 'json',
                'label' => 'Working Days',
                'description' => 'Select which days are regular working days',
                'validation_rules' => json_encode(['required', 'json']),
                'display_order' => 1,
            ],
            
            // TIME RULES
            [
                'key' => 'work_day_start_time',
                'category' => 'time_rules',
                'value' => '08:00',
                'type' => 'time',
                'label' => 'Work Day Start Time',
                'description' => 'Official start time of the work day',
                'validation_rules' => json_encode(['nullable', 'date_format:H:i']),
                'display_order' => 1,
            ],
            [
                'key' => 'work_day_end_time',
                'category' => 'time_rules',
                'value' => '17:00',
                'type' => 'time',
                'label' => 'Work Day End Time',
                'description' => 'Official end time of the work day',
                'validation_rules' => json_encode(['nullable', 'date_format:H:i']),
                'display_order' => 2,
            ],
            [
                'key' => 'grace_period_minutes',
                'category' => 'time_rules',
                'value' => '15',
                'type' => 'integer',
                'label' => 'Grace Period (Minutes)',
                'description' => 'Minutes allowed after start time before considered late',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:60']),
                'display_order' => 3,
            ],
            [
                'key' => 'minimum_work_hours',
                'category' => 'time_rules',
                'value' => '8',
                'type' => 'float',
                'label' => 'Minimum Work Hours Per Day',
                'description' => 'Minimum hours required for a full work day',
                'validation_rules' => json_encode(['nullable', 'numeric', 'min:1', 'max:24']),
                'display_order' => 4,
            ],
            [
                'key' => 'auto_clockout_enabled',
                'category' => 'time_rules',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Auto Clock-Out Enabled',
                'description' => 'Automatically clock out employees who forget',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'auto_clockout_time',
                'category' => 'time_rules',
                'value' => '23:59',
                'type' => 'time',
                'label' => 'Auto Clock-Out Time',
                'description' => 'Time to automatically clock out employees',
                'validation_rules' => json_encode(['nullable', 'date_format:H:i']),
                'display_order' => 6,
            ],

            // LOCATION RULES
            [
                'key' => 'require_gps',
                'category' => 'location_rules',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Require GPS for Clock-In',
                'description' => 'Employees must provide GPS coordinates to clock in',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'enable_geofencing',
                'category' => 'location_rules',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Enable Geofencing',
                'description' => 'Restrict clock-in to specific locations',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'allowed_locations',
                'category' => 'location_rules',
                'value' => '[]',
                'type' => 'json',
                'label' => 'Allowed Locations',
                'description' => 'List of allowed locations with coordinates and radius',
                'validation_rules' => json_encode(['nullable', 'json']),
                'display_order' => 3,
            ],
            [
                'key' => 'location_radius_meters',
                'category' => 'location_rules',
                'value' => '100',
                'type' => 'integer',
                'label' => 'Location Radius (Meters)',
                'description' => 'Acceptable distance from allowed location',
                'validation_rules' => json_encode(['nullable', 'integer', 'min:10', 'max:1000']),
                'display_order' => 4,
            ],
            [
                'key' => 'allow_remote_work',
                'category' => 'location_rules',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Allow Remote Work',
                'description' => 'Allow employees to clock in from any location',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],

            // PENALTIES
            [
                'key' => 'late_arrival_penalty_enabled',
                'category' => 'penalties',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Late Arrival Penalty Enabled',
                'description' => 'Apply penalty for late arrivals',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'late_arrival_penalty_amount',
                'category' => 'penalties',
                'value' => '0',
                'type' => 'float',
                'label' => 'Late Arrival Penalty Amount',
                'description' => 'Penalty amount for arriving late (currency)',
                'validation_rules' => json_encode(['required', 'numeric', 'min:0']),
                'display_order' => 2,
            ],
            [
                'key' => 'early_departure_penalty_enabled',
                'category' => 'penalties',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Early Departure Penalty Enabled',
                'description' => 'Apply penalty for leaving early',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'early_departure_penalty_amount',
                'category' => 'penalties',
                'value' => '0',
                'type' => 'float',
                'label' => 'Early Departure Penalty Amount',
                'description' => 'Penalty amount for leaving early (currency)',
                'validation_rules' => json_encode(['required', 'numeric', 'min:0']),
                'display_order' => 4,
            ],
            [
                'key' => 'missing_clockout_penalty_enabled',
                'category' => 'penalties',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Missing Clock-Out Penalty Enabled',
                'description' => 'Apply penalty for forgetting to clock out',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'missing_clockout_penalty_amount',
                'category' => 'penalties',
                'value' => '0',
                'type' => 'float',
                'label' => 'Missing Clock-Out Penalty Amount',
                'description' => 'Penalty amount for missing clock-out (currency)',
                'validation_rules' => json_encode(['required', 'numeric', 'min:0']),
                'display_order' => 6,
            ],

            // SHIFT MANAGEMENT
            [
                'key' => 'shifts_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Enable Shifts',
                'description' => 'Use shift-based attendance tracking',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'shift_mode',
                'category' => 'shifts',
                'value' => 'mandatory',
                'type' => 'string',
                'label' => 'Shift Assignment Mode',
                'description' => 'How shifts are assigned to employees',
                'validation_rules' => json_encode(['required', 'in:mandatory,optional,disabled']),
                'display_order' => 2,
            ],
            [
                'key' => 'grace_in_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Grace Period (In) Enabled',
                'description' => 'Allow buffer time for clock-in',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'grace_in_minutes',
                'category' => 'shifts',
                'value' => '10',
                'type' => 'integer',
                'label' => 'Grace Period (In) Minutes',
                'description' => 'Minutes allowed after shift start',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:60']),
                'display_order' => 4,
            ],
            [
                'key' => 'grace_out_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Grace Period (Out) Enabled',
                'description' => 'Allow buffer time for clock-out',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'grace_out_minutes',
                'category' => 'shifts',
                'value' => '10',
                'type' => 'integer',
                'label' => 'Grace Period (Out) Minutes',
                'description' => 'Minutes allowed before shift end',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:60']),
                'display_order' => 6,
            ],
            [
                'key' => 'night_shift_enabled',
                'category' => 'shifts',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Night Shift Support',
                'description' => 'Support for shifts crossing midnight',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 7,
            ],
            [
                'key' => 'night_time_start',
                'category' => 'shifts',
                'value' => '22:00',
                'type' => 'time',
                'label' => 'Night Time Start',
                'description' => 'Start of restricted night time range',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 8,
            ],
            [
                'key' => 'night_time_end',
                'category' => 'shifts',
                'value' => '06:00',
                'type' => 'time',
                'label' => 'Night Time End',
                'description' => 'End of restricted night time range',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 9,
            ],
            [
                'key' => 'rotational_shift_enabled',
                'category' => 'shifts',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Rotational Shifts',
                'description' => 'Auto-rotate employee shifts',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 8,
            ],
            [
                'key' => 'flexible_hours_enabled',
                'category' => 'shifts',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Flexible Hours',
                'description' => 'Allow employees to choose work timing',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 9,
            ],
            [
                'key' => 'split_shift_enabled',
                'category' => 'shifts',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Split Shifts',
                'description' => 'Support for shifts with breaks',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 10,
            ],
            [
                'key' => 'flexible_daily_target_hours',
                'category' => 'shifts',
                'value' => '8.0',
                'type' => 'float',
                'label' => 'Daily Target Hours',
                'description' => 'Required work duration per day for flexible shifts',
                'validation_rules' => json_encode(['required', 'numeric', 'min:0', 'max:24']),
                'display_order' => 11,
            ],
            [
                'key' => 'flexible_core_start_time',
                'category' => 'shifts',
                'value' => '10:00',
                'type' => 'time',
                'label' => 'Core Time Start',
                'description' => 'Start of mandatory presence window',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 12,
            ],
            [
                'key' => 'flexible_core_end_time',
                'category' => 'shifts',
                'value' => '15:00',
                'type' => 'time',
                'label' => 'Core Time End',
                'description' => 'End of mandatory presence window',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 13,
            ],
            [
                'key' => 'flexible_window_start',
                'category' => 'shifts',
                'value' => '06:00',
                'type' => 'time',
                'label' => 'Flex Window Start',
                'description' => 'Earliest allowed clock-in time',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 14,
            ],
            [
                'key' => 'flexible_window_end',
                'category' => 'shifts',
                'value' => '22:00',
                'type' => 'time',
                'label' => 'Flex Window End',
                'description' => 'Latest allowed clock-out time',
                'validation_rules' => json_encode(['required', 'date_format:H:i']),
                'display_order' => 15,
            ],

            // ATTENDANCE POLICIES
            [
                'key' => 'late_arrival_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Late Arrival Rules',
                'description' => 'Enable penalties for late arrival',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'early_checkout_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Early Checkout Rules',
                'description' => 'Enable penalties for early departure',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'half_day_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Half Day',
                'description' => 'Enable half day attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'absence_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Absence Tracking',
                'description' => 'Track employee absences',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 4,
            ],
            [
                'key' => 'overtime_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Overtime',
                'description' => 'Track and compensate extra hours',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 5,
            ],
            [
                'key' => 'wfh_enabled',
                'category' => 'policies',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Work from Home',
                'description' => 'Enable remote work attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 6,
            ],
            [
                'key' => 'comp_off_enabled',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Compensatory Off',
                'description' => 'Earn leave for extra work',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 7,
            ],
            // Late Arrival Detailed Config
            [
                'key' => 'late_arrival_grace_period',
                'category' => 'policies',
                'value' => '15',
                'type' => 'integer',
                'label' => 'Late Arrival Grace Period',
                'description' => 'Minutes allowed before marking as late',
                'validation_rules' => json_encode(['required', 'integer', 'min:0']),
                'display_order' => 8,
            ],
            [
                'key' => 'late_arrival_penalty_type',
                'category' => 'policies',
                'value' => 'none',
                'type' => 'string',
                'label' => 'Late Arrival Penalty Type',
                'description' => 'Action to take for late arrival',
                'validation_rules' => json_encode(['required', 'in:none,warning,deduction']),
                'display_order' => 9,
            ],
            [
                'key' => 'late_arrival_deduction_amount',
                'category' => 'policies',
                'value' => '0',
                'type' => 'float',
                'label' => 'Late Arrival Deduction Amount',
                'description' => 'Amount to deduct for late arrival',
                'validation_rules' => json_encode(['nullable', 'numeric', 'min:0']),
                'display_order' => 10,
            ],
            [
                'key' => 'late_arrival_deduction_type',
                'category' => 'policies',
                'value' => 'fixed',
                'type' => 'string',
                'label' => 'Late Arrival Deduction Type',
                'description' => 'How deduction is calculated',
                'validation_rules' => json_encode(['nullable', 'in:fixed,per_minute,percentage,half_day,full_day']),
                'display_order' => 11,
            ],
            // Early Checkout Detailed Config
            [
                'key' => 'early_checkout_grace_period',
                'category' => 'policies',
                'value' => '15',
                'type' => 'integer',
                'label' => 'Early Checkout Grace Period',
                'description' => 'Minutes allowed before marking as early checkout',
                'validation_rules' => json_encode(['required', 'integer', 'min:0']),
                'display_order' => 12,
            ],
            [
                'key' => 'early_checkout_penalty_type',
                'category' => 'policies',
                'value' => 'none',
                'type' => 'string',
                'label' => 'Early Checkout Penalty Type',
                'description' => 'Action to take for early checkout',
                'validation_rules' => json_encode(['required', 'in:none,warning,deduction']),
                'display_order' => 13,
            ],
            [
                'key' => 'early_checkout_deduction_amount',
                'category' => 'policies',
                'value' => '0',
                'type' => 'float',
                'label' => 'Early Checkout Deduction Amount',
                'description' => 'Amount to deduct for early checkout',
                'validation_rules' => json_encode(['nullable', 'numeric', 'min:0']),
                'display_order' => 14,
            ],
            [
                'key' => 'early_checkout_deduction_type',
                'category' => 'policies',
                'value' => 'fixed',
                'type' => 'string',
                'label' => 'Early Checkout Deduction Type',
                'description' => 'How deduction is calculated',
                'validation_rules' => json_encode(['nullable', 'in:fixed,per_minute,percentage,half_day,full_day']),
                'display_order' => 15,
            ],
            // Overtime Detailed Config
            [
                'key' => 'overtime_min_minutes',
                'category' => 'policies',
                'value' => '60',
                'type' => 'integer',
                'label' => 'Min Overtime Duration',
                'description' => 'Minimum minutes to count as overtime',
                'validation_rules' => json_encode(['required', 'integer', 'min:0']),
                'display_order' => 16,
            ],
            [
                'key' => 'overtime_rate_normal',
                'category' => 'policies',
                'value' => '1.25',
                'type' => 'float',
                'label' => 'Normal Overtime Rate',
                'description' => 'Rate multiplier for weekday overtime',
                'validation_rules' => json_encode(['required', 'numeric', 'min:1']),
                'display_order' => 17,
            ],
            [
                'key' => 'overtime_rate_night',
                'category' => 'policies',
                'value' => '1.5',
                'type' => 'float',
                'label' => 'Night Overtime Rate',
                'description' => 'Rate multiplier for night overtime',
                'validation_rules' => json_encode(['required', 'numeric', 'min:1']),
                'display_order' => 18,
            ],
            [
                'key' => 'overtime_rate_dayoff',
                'category' => 'policies',
                'value' => '2.0',
                'type' => 'float',
                'label' => 'Day Off Overtime Rate',
                'description' => 'Rate multiplier for weekend/day off overtime',
                'validation_rules' => json_encode(['required', 'numeric', 'min:1']),
                'display_order' => 19,
            ],
            [
                'key' => 'overtime_rate_holiday',
                'category' => 'policies',
                'value' => '2.5',
                'type' => 'float',
                'label' => 'Holiday Overtime Rate',
                'description' => 'Rate multiplier for public holiday overtime',
                'validation_rules' => json_encode(['required', 'numeric', 'min:1']),
                'display_order' => 20,
            ],

            // APPROVALS & WORKFLOW
            [
                'key' => 'missed_punch_approval_enabled',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Missed Punch Requests',
                'description' => 'Allow employees to request corrections',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'correction_approval_enabled',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Attendance Corrections',
                'description' => 'HR/Manager can modify attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'overtime_approval_enabled',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Overtime Approval',
                'description' => 'Require approval for overtime',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'auto_approval_enabled',
                'category' => 'approvals',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Auto-Approval',
                'description' => 'Automatically approve based on rules',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 4,
            ],
            [
                'key' => 'missed_punch_retroactive_limit',
                'category' => 'approvals',
                'value' => '7',
                'type' => 'integer',
                'label' => 'Missed Punch Retroactive Limit (Days)',
                'description' => 'How many days back employees can request corrections',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:30']),
                'display_order' => 5,
            ],
            [
                'key' => 'missed_punch_max_requests_per_month',
                'category' => 'approvals',
                'value' => '5',
                'type' => 'integer',
                'label' => 'Max Missed Punch Requests Per Month',
                'description' => 'Maximum number of requests an employee can make in a month',
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:31']),
                'display_order' => 6,
            ],
            [
                'key' => 'missed_punch_require_reason',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Require Reason for Missed Punch',
                'description' => 'Force employees to explain why they missed a punch',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 7,
            ],
            [
                'key' => 'missed_punch_approval_mode',
                'category' => 'approvals',
                'value' => 'manager',
                'type' => 'string',
                'label' => 'Missed Punch Approval Mode',
                'description' => 'Who approves missed punch requests',
                'validation_rules' => json_encode(['required', 'in:manager,hr,multi']),
                'display_order' => 8,
            ],
            // Attendance Corrections Detailed Config
            [
                'key' => 'correction_retroactive_limit',
                'category' => 'approvals',
                'value' => '30',
                'type' => 'integer',
                'label' => 'Correction Retroactive Limit',
                'description' => 'Days back allowed for manual modification',
                'validation_rules' => json_encode(['required', 'integer', 'min:0', 'max:365']),
                'display_order' => 9,
            ],
            [
                'key' => 'correction_require_reason',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Require Reason for Correction',
                'description' => 'Force admin to provide explanation',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 10,
            ],
            [
                'key' => 'correction_audit_trail_enabled',
                'category' => 'approvals',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Enable Correction Audit Trail',
                'description' => 'Keep detailed logs of manual changes',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 11,
            ],
            // Overtime Approval Workflow Detailed Config (Using policies category to match view)
            [
                'key' => 'ot_request_by_employee',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'OT Request by Employee',
                'description' => 'Allow employees to initiate OT requests',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 12,
            ],
            [
                'key' => 'ot_request_by_supervisor',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'OT Request by Supervisor',
                'description' => 'Allow supervisors to initiate OT requests',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 13,
            ],
            [
                'key' => 'ot_request_by_hr',
                'category' => 'policies',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'OT Request by HR',
                'description' => 'Allow HR to initiate OT requests',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 14,
            ],
            [
                'key' => 'ot_request_auto_generated',
                'category' => 'policies',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Auto-generate OT Requests',
                'description' => 'System automatically creates requests based on punches',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 15,
            ],
            [
                'key' => 'ot_request_timing',
                'category' => 'policies',
                'value' => 'both',
                'type' => 'string',
                'label' => 'OT Request Timing',
                'description' => 'When OT can be requested (pre, post, or both)',
                'validation_rules' => json_encode(['required', 'in:pre,post,both']),
                'display_order' => 16,
            ],
            [
                'key' => 'ot_level1_approver',
                'category' => 'policies',
                'value' => 'supervisor',
                'type' => 'string',
                'label' => 'Level 1 Approver',
                'description' => 'First person in approval chain',
                'validation_rules' => json_encode(['required', 'in:supervisor,department_head,hr']),
                'display_order' => 17,
            ],
            [
                'key' => 'ot_approval_mode',
                'category' => 'policies',
                'value' => 'sequential',
                'type' => 'string',
                'label' => 'OT Approval Mode',
                'description' => 'Sequential or parallel approval',
                'validation_rules' => json_encode(['required', 'in:sequential,parallel']),
                'display_order' => 18,
            ],
            [
                'key' => 'ot_require_punch_records',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Require Punch Records for OT',
                'description' => 'Validate OT against actual attendance',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 19,
            ],
            [
                'key' => 'ot_allow_manual',
                'category' => 'policies',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Allow Manual OT Entry',
                'description' => 'Allow entering OT hours manually',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 20,
            ],
            [
                'key' => 'ot_approval_hierarchy',
                'category' => 'policies',
                'value' => '1',
                'type' => 'integer',
                'label' => 'OT Approval Hierarchy Levels',
                'description' => 'Number of approval stages',
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:3']),
                'display_order' => 21,
            ],
            [
                'key' => 'ot_level2_approver',
                'category' => 'policies',
                'value' => 'department_head',
                'type' => 'string',
                'label' => 'Level 2 Approver',
                'description' => 'Second person in approval chain',
                'validation_rules' => json_encode(['nullable', 'string']),
                'display_order' => 22,
            ],
            [
                'key' => 'ot_level3_approver',
                'category' => 'policies',
                'value' => 'director',
                'type' => 'string',
                'label' => 'Level 3 Approver',
                'description' => 'Third person in approval chain',
                'validation_rules' => json_encode(['nullable', 'string']),
                'display_order' => 23,
            ],
            [
                'key' => 'ot_notify_approver',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Notify OT Approver',
                'description' => 'Send notification to approvers',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 24,
            ],
            [
                'key' => 'ot_notify_employee',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Notify Employee on OT Status',
                'description' => 'Send notification to employees on update',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 25,
            ],
            [
                'key' => 'ot_notify_hr',
                'category' => 'policies',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Notify HR on OT Approval',
                'description' => 'Send notification to HR department',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 26,
            ],
            [
                'key' => 'ot_enable_audit',
                'category' => 'policies',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Audit OT Changes',
                'description' => 'Log all OT approval modifications',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 27,
            ],
            [
                'key' => 'ot_payroll_sync',
                'category' => 'policies',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'OT Payroll Sync',
                'description' => 'Sync approved OT with payroll module',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 28,
            ],

            // INTEGRATIONS
            [
                'key' => 'leave_integration_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Leave Integration',
                'description' => 'Sync with leave management',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 1,
            ],
            [
                'key' => 'holiday_integration_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Holiday Calendar',
                'description' => 'Auto-mark holidays',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 2,
            ],
            [
                'key' => 'payroll_lock_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Payroll Lock',
                'description' => 'Lock attendance for payroll',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 3,
            ],
            [
                'key' => 'payroll_export_enabled',
                'category' => 'integrations',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Payroll Export',
                'description' => 'Export data for payroll processing',
                'validation_rules' => json_encode(['required', 'boolean']),
                'display_order' => 4,
            ],


            // WEB PORTAL CAPTURE METHOD
            [
                'key' => 'web_portal_require_gps',
                'category' => 'capture_methods',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Web Portal - Require GPS',
                'description' => 'Require GPS coordinates for web portal clock-in',
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'display_order' => 10,
            ],
            [
                'key' => 'web_portal_ip_whitelist',
                'category' => 'capture_methods',
                'value' => '',
                'type' => 'string',
                'label' => 'Web Portal - IP Whitelist',
                'description' => 'Allowed IP addresses for web portal (comma-separated)',
                'validation_rules' => json_encode(['nullable', 'string']),
                'display_order' => 11,
            ],
            [
                'key' => 'web_portal_allowed_hours_start',
                'category' => 'capture_methods',
                'value' => '',
                'type' => 'time',
                'label' => 'Web Portal - Allowed Hours Start',
                'description' => 'Earliest time for web portal clock-in',
                'validation_rules' => json_encode(['nullable', 'date_format:H:i']),
                'display_order' => 12,
            ],
            [
                'key' => 'web_portal_allowed_hours_end',
                'category' => 'capture_methods',
                'value' => '',
                'type' => 'time',
                'label' => 'Web Portal - Allowed Hours End',
                'description' => 'Latest time for web portal clock-in',
                'validation_rules' => json_encode(['nullable', 'date_format:H:i']),
                'display_order' => 13,
            ],

            // MANUAL ENTRY CONFIGURATION
            [
                'key' => 'manual_entry_permission_mode',
                'category' => 'manual_entry',
                'value' => 'roles',
                'type' => 'string',
                'label' => 'Permission Mode',
                'description' => 'Who can add attendance?',
                'validation_rules' => json_encode(['required', 'string', 'in:roles,everyone']),
                'display_order' => 20,
            ],
            [
                'key' => 'manual_entry_allowed_roles',
                'category' => 'manual_entry',
                'value' => '[]',
                'type' => 'json',
                'label' => 'Allowed Roles',
                'description' => 'Roles allowed to add manual attendance (if mode is roles)',
                'validation_rules' => json_encode(['nullable', 'array']),
                'display_order' => 21,
            ],
            [
                'key' => 'manual_entry_approval_policy',
                'category' => 'manual_entry',
                'value' => 'auto_approve',
                'type' => 'string',
                'label' => 'Approval Policy',
                'description' => 'Auto-approve or require approval',
                'validation_rules' => json_encode(['required', 'string', 'in:auto_approve,manual_approval']),
                'display_order' => 22,
            ],
            // New Approval Logic
            [
                'key' => 'manual_entry_approval_structure',
                'category' => 'manual_entry',
                'value' => 'single',
                'type' => 'string',
                'label' => 'Approval Structure',
                'description' => 'Single Approver or Hierarchical',
                'validation_rules' => json_encode(['required_if:manual_entry_approval_policy,manual_approval', 'string', 'in:single,hierarchical']),
                'display_order' => 23,
            ],
            [
                'key' => 'manual_entry_approver_entity',
                'category' => 'manual_entry',
                'value' => 'role',
                'type' => 'string',
                'label' => 'Approver Entity',
                'description' => 'Role or Individual User',
                'validation_rules' => json_encode(['required_if:manual_entry_approval_policy,manual_approval', 'string', 'in:role,individual']),
                'display_order' => 24,
            ],
            [
                'key' => 'manual_entry_approver_role_id',
                'category' => 'manual_entry',
                'value' => '',
                'type' => 'string',
                'label' => 'Approver Role',
                'description' => 'Selected Role for approval',
                'validation_rules' => json_encode(['nullable']),
                'display_order' => 25,
            ],
            [
                'key' => 'manual_entry_approver_user_id',
                'category' => 'manual_entry',
                'value' => '',
                'type' => 'string',
                'label' => 'Approver User',
                'description' => 'Selected User for approval',
                'validation_rules' => json_encode(['nullable']),
                'display_order' => 26,
            ],
            // Hierarchical Arrays
            [
                'key' => 'manual_entry_hierarchical_role_ids',
                'category' => 'manual_entry',
                'value' => '[]',
                'type' => 'json',
                'label' => 'Hierarchical Roles',
                'description' => 'Ordered chain of approver roles',
                'validation_rules' => json_encode(['nullable', 'array']),
                'display_order' => 27,
            ],
            [
                'key' => 'manual_entry_hierarchical_user_ids',
                'category' => 'manual_entry',
                'value' => '[]',
                'type' => 'json',
                'label' => 'Hierarchical Users',
                'description' => 'Ordered chain of approver users',
                'validation_rules' => json_encode(['nullable', 'array']),
                'display_order' => 28,
            ],
            
            // Common Data & Validation
            [
                'key' => 'manual_entry_track_project',
                'category' => 'manual_entry',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Track Project',
                'description' => 'Enable project selection for manual entry',
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'display_order' => 30,
            ],
            [
                'key' => 'manual_entry_require_project',
                'category' => 'manual_entry',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Require Project',
                'description' => 'Force project selection if tracking is enabled',
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'display_order' => 31,
            ],
            [
                'key' => 'manual_entry_require_reason',
                'category' => 'manual_entry',
                'value' => 'true',
                'type' => 'boolean',
                'label' => 'Require Reason',
                'description' => 'Require a reason/remark for manual entry',
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'display_order' => 32,
            ],
            [
                'key' => 'manual_entry_max_days_back',
                'category' => 'manual_entry',
                'value' => '30',
                'type' => 'integer',
                'label' => 'Max Days Back',
                'description' => 'Maximum days in the past allowed for entry',
                'validation_rules' => json_encode(['nullable', 'integer', 'min:10']),
                'display_order' => 33,
            ],
            [
                'key' => 'manual_entry_allow_future',
                'category' => 'manual_entry',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Allow Future Dates',
                'description' => 'Allow adding attendance for future dates',
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'display_order' => 34,
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('attendance_settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
