<?php

namespace Modules\Contacts\DataTables;

use Modules\Contacts\Models\CustomerStatement;
use Yajra\DataTables\Html\Button;
use Yajra\DataTables\Html\Column;
use Yajra\DataTables\EloquentDataTable;
use Yajra\DataTables\Services\DataTable;
use Yajra\DataTables\Html\Builder as HtmlBuilder;
use Illuminate\Database\Eloquent\Builder as QueryBuilder;

class CustomerStatementDataTable extends DataTable
{
    /**
     * Build the DataTable class.
     *
     * @param QueryBuilder $query Results from query() method.
     */
    public function dataTable(QueryBuilder $query): EloquentDataTable
    {
        return (new EloquentDataTable($query))
            ->editColumn('print_date', function ($row) {
                return format_date($row->print_date);
            })
             ->editColumn('date_from', function ($row) {
                 return format_date($row->date_from);
            })
             ->editColumn('date_to', function ($row) {
                 return format_date($row->date_to);
             })
             ->addColumn('customer_name', function ($row) {
                 return $row->contact ? $row->contact->name : '';
            })
             ->addColumn('added_by_name', function ($row) {
                 return $row->user ? $row->user->name : '';
            })
            ->addColumn('action', function ($row) {
                return view('contacts::customer_statements.action', ['id' => $row->id]);
            })->rawColumns(['action']);
    }

    /**
     * Get the query source of dataTable.
     */
    public function query(CustomerStatement $model): QueryBuilder
    {
        return $model->newQuery()->with(['contact', 'user']);
    }

    /**
     * Optional method if you want to use the html builder.
     */
    public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->setTableId('customer-statement-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->orderBy(0, 'desc')
                    ->buttons([
                        Button::make('excel'),
                        Button::make('csv'),
                        Button::make('pdf'),
                        Button::make('print'),
                        Button::make('reset'),
                        Button::make('reload')
                    ]);
    }

    /**
     * Get the dataTable columns definition.
     */
    public function getColumns(): array
    {
        return [
            Column::make('statement_no')->title('Statement No'),
            Column::make('customer_name')->title('Customer'),
            Column::make('date_from')->title('From'),
            Column::make('date_to')->title('To'),
            Column::make('print_date')->title('Generated On'),
            Column::make('added_by_name')->title('Generated By'),
            Column::computed('action')
                ->exportable(false)
                ->printable(false)
                ->addClass('text-end'),
        ];
    }

    /**
     * Get the filename for export.
     */
    protected function filename(): string
    {
        return 'CustomerStatement_' . date('YmdHis');
    }
}
